FROM fzinfz/anaconda3
# MAINTAINER Ferro Fang <fzinfz@gmail.com>

RUN conda install -y pyzmq pymongo pymysql mysql-connector-python psycopg2 sqlite

# RUN apt-get install nodejs-legacy npm libzmq3-dev && npm install -g ijavascript

# copy test notebooks and expose ports
ADD https://github.com/jupyter/docker-stacks/raw/master/base-notebook/jupyter_notebook_config.py /root/.jupyter/
COPY *.ipynb /root/
EXPOSE 8888


