FROM richarvey/nginx-php-fpm

RUN git clone https://github.com/breier/authentic.git && \
    mv authentic  /var/www/html/

ENV WEBROOT /var/www/html/authentic

# DB setup required. Demo: https://github.com/breier/authentic
