FROM golang as builder

RUN go get -v github.com/cyfdecyf/cow


FROM debian 

RUN mkdir -p /go/bin/
WORKDIR /go/bin/

COPY --from=builder /go/bin/cow .
EXPOSE 7777

# Any env variables started with an uncapitalized letter will be saved to rc file.
ENTRYPOINT exec env | grep '^[a-z]' > rc && sed -i 's/=/ = /g' rc && cow -rc rc

