FROM ubuntu

ENV TERM=xterm
RUN apt-get update && \
    apt-get install -y net-tools tcpdump  mtr nmap ncdu vim aria2 curl wget htop git iperf3 iputils-ping nload iftop bmon pciutils
RUN apt-get install -y nethogs 
