FROM debian
MAINTAINER Ferro Fang <fzinfz@gmail.com>

ENV TERM=xterm
ADD https://versaweb.dl.sourceforge.net/project/artica-squid/manual-setups/setup-proxy-debian7-v2.2.tar.gz . 
RUN ./setup-proxy-debian

