FROM fzinfz/jupyter 
MAINTAINER Ferro Fang <fzinfz@gmail.com>

RUN apt update && apt install -y xfce4 tightvncserver vim firefox-esr
ENV USER root

# chromium start error: Failed to move to new namespace
# xrdp - win10/7 client error: 0x2104

ADD https://raw.githubusercontent.com/alishtory/xsadmin/master/requirements.txt .
RUN sed -i 's/==/>=/' requirements.txt && \
    while read requirement; do conda install --yes $requirement; done < requirements.txt && \
    rm requirements.txt 
