FROM fzinfz/jupyter:jvm
MAINTAINER Ferro Fang <fzinfz@gmail.com>

#RUN wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie"  http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip

RUN git clone https://github.com/ligee/kotlin-jupyter.git

#RUN cd kotlin-jupyter && ./gradlew install


