FROM fzinfz/jupyter 
MAINTAINER Ferro Fang <fzinfz@gmail.com>

ENV USER root
RUN apt update && apt install -y i3 rxvt \
	 tightvncserver xrdp \
	firefox-esr chromium 

RUN sed -i 's!/etc/X11/Xsession!#/etc/X11/Xsession!' ~/.vnc/xstartup && \
    echo 'i3 &' >> ~/.vnc/xstartup && \
    cp -f  /etc/i3/config ~/.i3/

