FROM fzinfz/jupyter 
MAINTAINER Ferro Fang <fzinfz@gmail.com>

RUN apt update && apt install -y xfce4 tightvncserver vim firefox-esr
ENV USER root

# chromium start error: Failed to move to new namespace
# xrdp - win10/7 client error: 0x2104
