FROM fzinfz/jupyter 
MAINTAINER Ferro Fang <fzinfz@gmail.com>

ENV USER root
RUN apt update && apt install -y i3 rxvt \
	 tightvncserver xrdp 
# xrdp not work, error: 0x2104

# install web browsers
RUN curl https://raw.githubusercontent.com/fzinfz/scripts/master/install-browser-debian8.sh | bash

ADD i3wm-vnc-init.sh .
RUN chmod +x *.sh
