FROM ocaml/opam:ubuntu-14.04_ocaml-4.05.0

RUN git clone https://github.com/frenetic-lang/frenetic && \
    opam pin add frenetic ./frenetic -n -k git && \
    opam install -y frenetic 

# RUN	sudo pip install -e  src/frenetic/lang/python

