FROM ubuntu:14.04
MAINTAINER Ferro Fang <fzinfz@gmail.com>

ENV TERM=xterm
RUN apt update && apt install -y wget

ADD http://download.flowbat.com/silkonabox.sh .

RUN chmod +x  silkonabox.sh 
RUN printf 'y\n1\ny\ny\n' | ./silkonabox.sh
