FROM richarvey/nginx-php-fpm

RUN git clone -b master https://github.com/orvice/ss-panel.git 

WORKDIR  /ss-panel 

RUN curl -sS https://getcomposer.org/installer | php && \
    php composer.phar  install

RUN chmod -R 777 storage

RUN apk add --no-cache mysql-client     

RUN cp .env.example .env && \
    sed -i "s/^db_host.*/db_host = 'mysql'/" .env

COPY orvice-v3.nginx-default.conf /etc/nginx/sites-enabled/default.conf
