# https://github.com/laobubu/ssland/wiki/Install

FROM python:2.7

ADD https://raw.githubusercontent.com/laobubu/ssland/universal/requirements.txt /
RUN pip install -r /requirements.txt

RUN git clone https://github.com/laobubu/ssland.git
WORKDIR /ssland

ADD ssland.shadowsocks.json /etc/shadowsocks.json
