FROM python

RUN git clone https://github.com/fzinfz/django-phone.git
WORKDIR django-phone

RUN pip install -r requirements.txt

RUN python manage.py makemigrations && \
    python manage.py migrate && \
    python manage.py collectstatic

CMD ['./run_dev.sh']
