FROM gcc

RUN apt update && apt install -y \
	automake autotools-dev g++ git libcurl4-gnutls-dev \
        libfuse-dev libssl-dev libxml2-dev make pkg-config

RUN git clone https://github.com/tencentyun/cosfs-v4.2.1.git 

RUN cd cosfs* && \
./autogen.sh && \
./configure && \
make && \
make install
