FROM python:3

RUN pip install django uwsgi \
	django-bootstrap3 djangorestframework django-filter  \
	django-registration-redux  \
	django-markdownx mistune \
	django-qr-code pillow \
	django-captcha-admin  django-simple-captcha django-recaptcha django-recaptcha2

VOLUME /src
EXPOSE 8000
