FROM gcc
RUN apt update
RUN apt install -y vim \
	dpkg-dev lsb-release \
	bc libelf-dev git libfdt-dev libpixman-1-dev libssl-dev vim socat libsdl1.2-dev libspice-server-dev autoconf libtool xtightvncviewer tightvncserver x11vnc libsdl1.2-dev uuid-runtime uuid uml-utilities bridge-utils python-dev liblzma-dev libc6-dev
