FROM python

RUN git clone https://github.com/fzinfz/django-phone.git
WORKDIR django-phone
RUN pip install -r requirements.txt && \
    python manage.py makemigrations && \
    python manage.py migrate

CMD ['./run_dev.sh']
