FROM python:3

RUN pip install django uwsgi \
	pillow requests mistune \
	djangorestframework \
	django-bootstrap3 \
	django-filter  \
	django-registration-redux  \
	django-markdownx \
	django-qr-code \
	django-captcha-admin \
	django-simple-captcha \
	django-recaptcha \
	django-recaptcha2

RUN apt update && apt -y install libz-dev libjpeg-dev libfreetype6-dev python3-dev gettext vim

VOLUME /src
WORKDIR /src
ENV PYTHONUNBUFFERED 1
EXPOSE 8000
