FROM python:2

RUN git clone https://github.com/tolerious/django-wechat.git                                                                                            
WORKDIR ./django-wechat
RUN pip install -r requirement.txt  # django 1.7.7
#    python manage.py makemigrations && python manage.py migrate
RUN apt update && apt install -y vim
