FROM python:3-jessie

RUN echo "deb http://deb.debian.org/debian jessie-backports main\n" > /etc/apt/sources.list.d/jessie-backports.list && \
    echo "deb http://deb.debian.org/debian jessie-backports-sloppy main" >> /etc/apt/sources.list.d/jessie-backports.list && \
    apt update && apt -y -t jessie-backports-sloppy install shadowsocks-libev simple-obfs rng-tools

RUN pip3 install git+https://github.com/shadowsocks/shadowsocks.git@master && \
    pip3 install git+https://github.com/sorz/ssmanager.git && \
    pip3 install git+https://github.com/fzinfz/ssmanager-nopanel.git

ENV PYTHONUNBUFFERED 1

ENTRYPOINT ["ssmanager-nopanel"]

