FROM mritd/shadowsocks

RUN apk add --no-cache python3 git wget
RUN wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm get-pip.py
RUN pip3 install requests argparse git+https://github.com/sorz/ssmanager.git
RUN git clone https://github.com/fzinfz/ssmanager-nopanel.git
RUN apk add --no-cache vim
WORKDIR ./ssmanager-nopanel
