FROM fzinfz/ss

RUN pip3 install git+https://github.com/shadowsocks/shadowsocks.git@master && \
    pip3 install git+https://github.com/sorz/ssmanager.git && \
    pip3 install git+https://github.com/fzinfz/ssmanager-nopanel.git

ENTRYPOINT ["ssmanager-nopanel"]
