FROM python:3

ENV SS_VERSION 2.9.1

RUN wget --no-check-certificate https://github.com/shadowsocks/shadowsocks/archive/$SS_VERSION.tar.gz && \
    tar -zxvf $SS_VERSION.tar.gz && rm *.tar.gz  &&  cd shadowsocks-* && \
    python setup.py install

# lack libsodium, official: 
# https://github.com/shadowsocks/shadowsocks/blob/master/Dockerfile
