FROM python:3-alpine
MAINTAINER Ferro Fang <fzinfz@gmail.com>

RUN apk add --no-cache --virtual .build-deps \
	git && \
    git clone https://github.com/alishtory/xsadmin.git && \
    apk del .build-deps 

WORKDIR xsadmin

RUN apk add --no-cache python3-dev libffi-dev
RUN pip3 install --upgrade setuptools && pip3 install -r requirements.txt
