FROM fzinfz/shadowsocks-xsadmin

ENV SSH_PORT 23
ENV RootPassword RootPassword
RUN curl https://raw.githubusercontent.com/fzinfz/scripts/master/sshd-enable--port--RootPassword | bash -s ${SSH_PORT} ${RootPassword}
